export const NAVBAR_LINKS = [
    {
        id:"1",
        title:"ABOUT",
        linkTo:"/"
    },
    {
        id:"2",
        title:"PROJECTS",
        linkTo:"/projects"
    },
    {
        id:"3",
        title:"EDUCATION",
        linkTo:"/education"
    },
    {
        id:"4",
        title:"SKILLS",
        linkTo:"/skills"
    },
    {
        id:"5",
        title:"INTERESTS",
        linkTo:"/interests"
    },
    {
        id:"6",
        title:"SOCIAL",
        linkTo:"/social"
    }
]